// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio-concepts/ConceptA.tsx": () => import("../components/mockups/portfolio-concepts/ConceptA.tsx"),
  "./components/mockups/portfolio-concepts/ConceptB.tsx": () => import("../components/mockups/portfolio-concepts/ConceptB.tsx"),
  "./components/mockups/portfolio-concepts/ConceptC.tsx": () => import("../components/mockups/portfolio-concepts/ConceptC.tsx"),
  "./components/mockups/winxp/WinXPPortfolio.tsx": () => import("../components/mockups/winxp/WinXPPortfolio.tsx"),
  "./components/mockups/portfolio-quirky/QuirkyA.tsx": () => import("../components/mockups/portfolio-quirky/QuirkyA.tsx"),
  "./components/mockups/portfolio-quirky/QuirkyB.tsx": () => import("../components/mockups/portfolio-quirky/QuirkyB.tsx"),
  "./components/mockups/portfolio-quirky/QuirkyC.tsx": () => import("../components/mockups/portfolio-quirky/QuirkyC.tsx"),
  "./components/mockups/portfolio-quirky/QuirkyD.tsx": () => import("../components/mockups/portfolio-quirky/QuirkyD.tsx"),
  "./components/mockups/portfolio-quirky/QuirkyE.tsx": () => import("../components/mockups/portfolio-quirky/QuirkyE.tsx"),
  "./components/mockups/portfolio-quirky/QuirkyF.tsx": () => import("../components/mockups/portfolio-quirky/QuirkyF.tsx"),
  "./components/mockups/work-redesign/SoftNeutral.tsx": () => import("../components/mockups/work-redesign/SoftNeutral.tsx"),
  "./components/mockups/work-redesign/SwissGrid.tsx": () => import("../components/mockups/work-redesign/SwissGrid.tsx"),
  "./components/mockups/work-redesign/WarmEditorial.tsx": () => import("../components/mockups/work-redesign/WarmEditorial.tsx")
};
