// This file is auto-generated by mockupPreviewPlugin.ts.
type ModuleMap = Record<string, () => Promise<Record<string, unknown>>>;
export const modules: ModuleMap = {
  "./components/mockups/portfolio-concepts/ConceptA.tsx": () => import("../components/mockups/portfolio-concepts/ConceptA.tsx"),
  "./components/mockups/portfolio-concepts/ConceptB.tsx": () => import("../components/mockups/portfolio-concepts/ConceptB.tsx"),
  "./components/mockups/portfolio-concepts/ConceptC.tsx": () => import("../components/mockups/portfolio-concepts/ConceptC.tsx")
};
